-- migrate:up
CREATE TABLE products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) UNIQUE NOT NULL,
  price DECIMAL(10, 3) NOT NULL,
  gender VARCHAR(20) NOT NULL,
  description TEXT NOT NULL,
  is_new BOOLEAN NOT NULL DEFAULT FALSE,
  discount_rate INT NOT NULL DEFAULT 0,
  release_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE products;